[migrate] MainNavigator, Downloader, ScrollList, Home Page
idea2app/React-MobX-MUI-ts pull request #1
Opened 2024-10-01 16:56 UTC by Soecka

[migrate] MainNavigator, Downloader, ScrollList, Home Page
[add] ColorModeDropdown for switch dark mode
[update] eslint.config.mjs

2024-10-02 06:57 UTC, TechQuery requested changes
分页表格文件可以不删，方便下个 PR 对比差异。

2024-10-02 06:57 UTC, TechQuery commented on src/component/Downloader.tsx
> +        >{`${Math.round(task.percent)}%`}</Typography>
```suggestion
        >{Math.round(task.percent)}%</Typography>
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Git/Card.tsx
> +        height: '100%',
组件尽量只定义自己的样式，和外面其它元素的关系从 `className`、`style` 传入，更有通用性。

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +export default function ColorModeIconDropdown() {
```suggestion
 * @see {@link https://github.com/mui/material-ui/blob/79bfe9a38201ec639f7b65c3e158c9fe565b204b/docs/data/material/getting-started/templates/shared-theme/ColorModeIconDropdown.tsx#L10}
 */
export function ColorSwitch() {
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }[resolvedMode];
对象字面量部分放到组件外面。

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
```suggestion
  const handleOpen = ({ currentTarget }: MouseEvent<HTMLElement>) => setAnchorEl(currentTarget);

  const handleClose = () => setAnchorEl(null);

  const handleMode = (targetMode: 'system' | 'light' | 'dark') => () => {
    setMode(targetMode);
    handleClose();
  };

  if (!mode)
    return (
      <Box
        data-screenshot="toggle-mode"
        sx={theme => ({
          verticalAlign: 'bottom',
          display: 'inline-flex',
          width: '2.25rem',
          height: '2.25rem',
          borderRadius: (theme.vars || theme).shape.borderRadius,
          border: '1px solid',
          borderColor: (theme.vars || theme).palette.divider
        })}
      />
    );
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +            }
```suggestion
            sx: { my: '4px' }
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
```suggestion
export const MUIIcon: FC<SvgIconProps> = props => (
    <SvgIcon {...props}>
      <path
        fill="#007FFF"
        fillRule="evenodd"
        clipRule="evenodd"
        d="M30.343 21.976a1 1 0 00.502-.864l.018-5.787a1 1 0 01.502-.864l3.137-1.802a1 1 0 011.498.867v10.521a1 1 0 01-.502.867l-11.839 6.8a1 1 0 01-.994.001l-9.291-5.314a1 1 0 01-.504-.868v-5.305c0-.006.007-.01.013-.007.005.003.012 0 .012-.007v-.006c0-.004.002-.008.006-.01l7.652-4.396c.007-.004.004-.015-.004-.015a.008.008 0 01-.008-.008l.015-5.201a1 1 0 00-1.5-.87l-5.687 3.277a1 1 0 01-.998 0L6.666 9.7a1 1 0 00-1.499.866v9.4a1 1 0 01-1.496.869l-3.166-1.81a1 1 0 01-.504-.87l.028-16.43A1 1 0 011.527.86l10.845 6.229a1 1 0 00.996 0L24.21.86a1 1 0 011.498.868v16.434a1 1 0 01-.501.867l-5.678 3.27a1 1 0 00.004 1.735l3.132 1.783a1 1 0 00.993-.002l6.685-3.839zM31 7.234a1 1 0 001.514.857l3-1.8A1 1 0 0036 5.434V1.766A1 1 0 0034.486.91l-3 1.8a1 1 0 00-.486.857v3.668z"
      />
    </SvgIcon>
  );
```
放到独立文件。

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +  @observable accessor menuAnchor: HTMLButtonElement = null;
```suggestion
  @observable accessor menuAnchor: HTMLButtonElement | undefined;
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +      { menuAnchor: anchorEl } = this;
```suggestion
      { menuAnchor } = this;
```
看上下文没必要改名

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/themePrimitive.ts
> +  interface PaletteColor extends ColorRange {}
```suggestion
  interface PaletteColor extends Record<'50' | `${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}00`, string> {}
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/themePrimitive.ts
> +      },
```suggestion
      grey: { ...gray },
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/themePrimitive.ts
> +      fontFamily: ['"Roboto", "sans-serif"'].join(','),
```suggestion
      fontFamily: '"Roboto", "sans-serif"',
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/Layout/themePrimitive.ts
> +export const shadows = defaultShadows;
```suggestion
export const shadows: Shadows = ['var(--mui-palette-baseShadow)', ...defaultTheme.shadows.slice(1)];
```

2024-10-02 06:57 UTC, TechQuery commented on src/component/TSXSample.tsx
> +    {/* <CodeBlock language="tsx">{children}</CodeBlock> */}
准备咋搞？

2024-10-02 06:57 UTC, TechQuery commented on src/model/rich-edit.json
>  }
富文本编辑器怎么搞？

2024-10-02 06:57 UTC, TechQuery commented on src/page/App.tsx
>  export function App() {
```suggestion
export const App = () =>
```

2024-10-02 08:14 UTC, Soecka commented on src/component/TSXSample.tsx
> +    {/* <CodeBlock language="tsx">{children}</CodeBlock> */}
先删了，IdeaReact 那个 PR 没做完

2024-10-02 08:14 UTC, Soecka commented on src/model/rich-edit.json
>  }
先删了，不搞

2024-10-02 08:20 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +export default function ColorModeIconDropdown() {
他不是和 `@see` 绑定用的，这个组件整个是 copy 过来的

2024-10-02 08:22 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }[resolvedMode];
resolveMode 里面包含 mode 和 systemMode，两者是 state

2024-10-02 08:29 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
他这边 ``handleClose`` 本来是要往父级组件往上传，加上一些 keyboard 事件整体在顶级 APP wrapper 做判断处理的，因为目前的实现 dropdown 会让页面无法滚动，所以临时写一下

直接引用过来的组件建议不改动……

2024-10-02 08:36 UTC, Soecka commented on src/component/Git/Card.tsx
> +        height: '100%',
这边一般不用 className，除非自己再去定义一套实用样式类，我不想用 style component 包一层，所以直接这样写了

2024-10-02 08:42 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
https://eslint.org/docs/latest/rules/arrow-body-style#never

可以把 eslint rule 可以更改为更严格的配置，只要单行就去掉弯括号，现在的配置 ``as needed`` 应该是如果 return 函数可以用弯括号，返回值和对象都必须去掉弯括号

2024-10-02 08:49 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
但是这两者其实是有细微的差别，简写的 arrow function 必定会返回 setMode，

2024-10-02 09:07 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
https://html-eslint.org/docs/rules/sort-attrs

放到独立文件的情况是，你不知道这一堆里面哪个有没有被引用，之后不好删除,目前的规则内，同文件未使用是可以检测出来的，typescript eslint 本来加了一个export检查规则，后来取消了（https://github.com/typescript-eslint/typescript-eslint/issues/371#issuecomment-1770092707），推荐使用 knip
https://knip.dev/overview/getting-started

2024-10-02 09:10 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +  @observable accessor menuAnchor: HTMLButtonElement = null;
这里 null 语义上会不会更好一点，相当于是 menu 列表的 dialog 锚点元素，这些都是官方示例里面引用的

2024-10-02 09:11 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +      { menuAnchor: anchorEl } = this;
应该是重命名 bug

2024-10-02 09:14 UTC, Soecka commented on src/component/Layout/themePrimitive.ts
> +      fontFamily: ['"Roboto", "sans-serif"'].join(','),
这样写是错的，我改过了一下

``["Roboto", "sans-serif"].join(',')``

2024-10-02 09:23 UTC, TechQuery commented on src/component/Git/Card.tsx
> +        height: '100%',
> 这边一般不用 className，除非自己再去定义一套实用样式类，我不想用 style component 包一层，所以直接这样写了

标准的东西和各种框架风格没关系：
```tsx
export type GitCardProps = HTMLAttributes<HTMLElement> & CardProps;

export const GitCard: FC<GitCardProps> = ({ className, style, ...props }) =>
  <Card className={className} style={style} {...props} />;
```

2024-10-02 09:24 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +export default function ColorModeIconDropdown() {
> 他不是和 `@see` 绑定用的，这个组件整个是 copy 过来的

https://jsdoc.app/tags-see

2024-10-02 09:25 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }[resolvedMode];
> resolveMode 里面包含 mode 和 systemMode，两者是 state

我说的是**对象字面量**部分，不是”使用对象字面量“部分。

2024-10-02 09:29 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
> 直接引用过来的组件建议不改动……

这又不是上游库本身需要跟随版本更新，示例代码写得随便一些很常见，自己拿来用就要融入项目代码。

2024-10-02 09:32 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> 放到独立文件的情况是，你不知道这一堆里面哪个有没有被引用，之后不好删除

按这样的思路，整个项目就不要分模块了，代码全放一个文件最方便检测 unused……

2024-10-02 09:34 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +  @observable accessor menuAnchor: HTMLButtonElement = null;
> 这里 null 语义上会不会更好一点，相当于是 menu 列表的 dialog 锚点元素，这些都是官方文档示例里面引用的

那就要写对类型：
```suggestion
  @observable accessor menuAnchor: HTMLButtonElement | null = null;
```

2024-10-02 09:35 UTC, TechQuery commented on src/component/Layout/themePrimitive.ts
> +      fontFamily: ['"Roboto", "sans-serif"'].join(','),
> ["Roboto", "sans-serif"].join(',')

可以更简单：
```suggestion
      fontFamily: ['Roboto‘, ’sans-serif'] + '',
```

2024-10-02 18:09 UTC, Soecka commented on src/component/Git/Card.tsx
> +        height: '100%',
这个标准在此不适用，className 没有，除非引入 Tailwind 或自己手写 ``h-100``，style 内联样式不好维护，html DOM 很难看，不好调试，无法应用于伪类和悬停这类状态

这边的写法一般是 style() 传 props ，所以我才说为了写页面就写了一个，如果有复用的场景再抽

```
interface StyledCard extends CardProps {
  height?: string;
}

const StyledCard = styled(Card, {
  shouldForwardProp: prop => prop !== 'height'
})<CardOwnProps>(({ theme }) => ({
  variants: [
    {
      props: ({ height }) => height,
      style: {...}
    }
  ]
}));

<StyledCard height="" />;

```

2024-10-02 18:17 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +export default function ColorModeIconDropdown() {
文档里面就是没有绑定啊，``@see`` 还可以直接引用页面内组件

link 示例页面也有搭配 `check out {@link xxx}` 的用法

2024-10-02 18:22 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +export default function ColorModeIconDropdown() {
我直接用 `@copyright` 搭配 `@link `

2024-10-02 18:50 UTC, TechQuery commented on src/component/Git/Card.tsx
> +        height: '100%',
> 这边的写法一般是 style() 传 props ，所以我才说为了写页面就写了一个，如果有复用的场景再抽
> 
> ```
> interface StyledCard extends CardProps {
>   height?: string;
> }
> 
> const StyledCard = styled(Card, {
>   shouldForwardProp: prop => prop !== 'height'
> })<CardOwnProps>(({ theme }) => ({
>   variants: [
>     {
>       props: ({ height }) => height,
>       style: {...}
>     }
>   ]
> }));
> 
> <StyledCard height="" />;
> 
> ```

那我只能说这种写法是极端难以学习和维护的，不符合 Web “渐进增强、优雅降级”的基本原则，会成为我拒绝使用 MUI 这一类组件库的重要理由。

总的来说，在 Web 领域，我支持任何类型的创新，但不支持砍掉原生兼容性的强制改变。

2024-10-02 18:50 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +  @observable accessor menuAnchor: HTMLButtonElement = null;
` @observable accessor menuAnchor: PopoverProps['anchorEl'] = null;`

2024-10-02 18:58 UTC, Soecka commented on src/component/Layout/themePrimitive.ts
> +export const shadows = defaultShadows;
我不知道原先为什么这样写，上面还加了两行注释

```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
```

2024-10-02 18:59 UTC, Soecka commented on src/page/App.tsx
>  export function App() {
这个是为什么？

2024-10-02 19:08 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
这个就是 brand icon svg，和导航栏强相关，用 mui SvgIcon 组件注入 path 生成

2024-10-03 04:06 UTC, TechQuery commented on src/page/App.tsx
>  export function App() {
> 这个是为什么？

删掉 `{ return }` 少一层缩进。

2024-10-03 04:08 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> 这个就是 brand icon svg，和导航栏强相关，用 mui SvgIcon 组件注入 path 生成

那这个函数组件的名字起得就太过通用

2024-10-03 13:35 UTC, Soecka commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
> > 直接引用过来的组件建议不改动……
> 
> 这又不是上游库本身需要跟随版本更新，示例代码写得随便一些很常见，自己拿来用就要融入项目代码。

这不是示例代码，这是他们模板项目的代码，https://mui.com/material-ui/getting-started/templates/dashboard/

2024-10-03 13:41 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> 按这样的思路，整个项目就不要分模块了，代码全放一个文件最方便检测 unused……
> 
> 语义上和导航栏组件不相干的组件就要独立出来。

那为什么打包库要做 treeShaking ……这样处理不是代码仓库体积也会小一点吗

2024-10-03 13:58 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> > 这个就是 brand icon svg，和导航栏强相关，用 mui SvgIcon 组件注入 path 生成
> 
> 那这个函数组件的名字起得就太过通用，而且完全可以写为导航栏类组件的一个方法，以体现其强相关性。

这样封装比较方便，比如，切换暗色模式时，如果需要更改 svg 模式，可以像下面这样写

```
<BrandIcon color="action" sx={{ color: pink[500] }} fontSize="large"  />
```

如果是类组件，就会变成 

```
{this.renderBrandIcon(xxxx)}
```

2024-10-03 14:00 UTC, Soecka commented on src/page/App.tsx
>  export function App() {
写了 function eslint 的规则就不起作用了……

2024-10-03 14:10 UTC, Soecka commented on src/page/App.tsx
>  export function App() {
[restful-table](https://github.com/idea2app/MobX-RESTful-table/blob/master/source/ScrollBoundary.tsx#L15) 那个库
```
function touch(edge: EdgePosition, onTouch: TouchHandler) {
  return (node: HTMLElement | null) =>
    node &&
    new IntersectionObserver(([{ isIntersecting }]) => isIntersecting && onTouch(edge)).observe(
      node
    );
}
```
是不是可以改写为
```
const touch = (edge: EdgePosition, onTouch: TouchHandler) => (node: HTMLElement | null) =>
  node &&
  new IntersectionObserver(([{ isIntersecting }]) => isIntersecting && onTouch(edge)).observe(node);
```

2024-10-03 14:38 UTC, TechQuery commented on src/component/Layout/Nav/ColorModeDropdown.tsx
> +  }
> 这不是示例代码，这是他们官方模板项目共用的[主题切换](https://github.com/mui/material-ui/blob/79bfe9a38201ec639f7b65c3e158c9fe565b204b/docs/data/material/getting-started/templates/shared-theme/ColorModeIconDropdown.tsx#L10)，https://mui.com/material-ui/getting-started/templates/dashboard/

模板就是一种示例代码，官方只做演示、不负全责。

2024-10-03 14:41 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> 那为什么打包库要做 treeShaking ……这样处理不是代码仓库体积也会小一点吗

Tree shaking 能处理多模块引用。

2024-10-03 14:42 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +}
> ```tsx
> <BrandIcon color="action" sx={{ color: pink[500] }} fontSize="large"  />
> ```

组件这么命名就对了。

2024-10-03 14:44 UTC, TechQuery commented on src/page/App.tsx
>  export function App() {
> [restful-table](https://github.com/idea2app/MobX-RESTful-table/blob/master/source/ScrollBoundary.tsx#L15) 那个库
> ```
> function touch(edge: EdgePosition, onTouch: TouchHandler) {
>   return (node: HTMLElement | null) =>
>     node &&
>     new IntersectionObserver(([{ isIntersecting }]) => isIntersecting && onTouch(edge)).observe(
>       node
>     );
> }
> ```
> 是不是可以改写为
> ```
> const touch = (edge: EdgePosition, onTouch: TouchHandler) => (node: HTMLElement | null) =>
>   node &&
>   new IntersectionObserver(([{ isIntersecting }]) => isIntersecting && onTouch(edge)).observe(node);
> ```
> 

是可以，但多层箭头函数容易看不清几层函数，和 JSX 缩进太多不一样。

2024-10-04 14:52 UTC, TechQuery requested changes

2024-10-04 14:52 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +    ></path>
```suggestion
import { Component, FC } from 'react';

import { mainNavLinks } from '../../../meta';
import { i18n, LanguageName } from '../../../model/Translation';
import ColorModeIconDropdown from './ColorModeDropdown';

export const BrandIcon: FC<SvgIconProps> = props => (
  <SvgIcon {...props}>
    <path
      fill="#007FFF"
      fillRule="evenodd"
      clipRule="evenodd"
      d="M30.343 21.976a1 1 0 00.502-.864l.018-5.787a1 1 0 01.502-.864l3.137-1.802a1 1 0 011.498.867v10.521a1 1 0 01-.502.867l-11.839 6.8a1 1 0 01-.994.001l-9.291-5.314a1 1 0 01-.504-.868v-5.305c0-.006.007-.01.013-.007.005.003.012 0 .012-.007v-.006c0-.004.002-.008.006-.01l7.652-4.396c.007-.004.004-.015-.004-.015a.008.008 0 01-.008-.008l.015-5.201a1 1 0 00-1.5-.87l-5.687 3.277a1 1 0 01-.998 0L6.666 9.7a1 1 0 00-1.499.866v9.4a1 1 0 01-1.496.869l-3.166-1.81a1 1 0 01-.504-.87l.028-16.43A1 1 0 011.527.86l10.845 6.229a1 1 0 00.996 0L24.21.86a1 1 0 011.498.868v16.434a1 1 0 01-.501.867l-5.678 3.27a1 1 0 00.004 1.735l3.132 1.783a1 1 0 00.993-.002l6.685-3.839zM31 7.234a1 1 0 001.514.857l3-1.8A1 1 0 0036 5.434V1.766A1 1 0 0034.486.91l-3 1.8a1 1 0 00-.486.857v3.668z"
    />
```

2024-10-04 14:52 UTC, TechQuery commented on src/page/Pagination.tsx
分页表格文件可以不删，方便下个 PR 对比差异。

2024-10-04 15:00 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +    ></path>
不解构也要用 FC 吗？

2024-10-04 15:08 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +    ></path>
```
"react/self-closing-comp": ["error", {
  "component": true,
  "html": true
}]
```

2024-10-04 15:19 UTC, TechQuery commented on src/component/Layout/Nav/MainNavigator.tsx
> +    ></path>
> 不解构也要用 FC 吗？

组件名和 props 类型紧挨比较清晰

2024-10-04 15:21 UTC, Soecka commented on src/component/Layout/Nav/MainNavigator.tsx
> +    ></path>
我探进去看了一下，FC 方便 React Dev Tool debug，还有 defaultProps 和 displayName 等属性

2024-10-04 15:47 UTC, TechQuery approved these changes

2024-10-04 15:52 UTC, merged